# Generated by Django 5.0.1 on 2024-01-05 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('type', models.CharField(choices=[('vip', 'VIP'), ('std', 'standart'), ('big', 'big')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('duration', models.DurationField()),
                ('genre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Projections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('Hall', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.hall')),
                ('movie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.movies')),
            ],
        ),
        migrations.CreateModel(
            name='Seats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.IntegerField()),
                ('col', models.CharField(max_length=1)),
                ('is_available', models.BooleanField(default=True)),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.hall')),
            ],
        ),
        migrations.CreateModel(
            name='Seats_for_projections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_empty', models.BooleanField(default=True)),
                ('projection', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.projections')),
                ('seat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.seats')),
            ],
        ),
    ]
