# Generated by Django 5.0.1 on 2024-01-05 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Movies',
            new_name='Movie',
        ),
        migrations.RenameModel(
            old_name='Projections',
            new_name='Projection',
        ),
        migrations.RenameModel(
            old_name='Seats',
            new_name='Seat',
        ),
        migrations.RenameModel(
            old_name='Seats_for_projections',
            new_name='Seats_for_projection',
        ),
    ]
