# Generated by Django 4.0.4 on 2024-01-24 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_movie_img_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='img_url',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
