# Generated by Django 4.0.4 on 2024-01-26 12:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_movie_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='projection',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='projection',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
