# Generated by Django 4.0.4 on 2024-02-02 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_ticket_delete_seats_for_projection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='is_empty',
        ),
    ]
