# Generated by Django 4.0.4 on 2024-02-09 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_remove_ticket_is_empty'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'cash'), ('card', 'card')], max_length=10, null=True),
        ),
    ]
