# Generated by Django 5.0.2 on 2024-02-17 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_ticket_payment_method'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projection',
            old_name='Hall',
            new_name='hall',
        ),
    ]
